{
 "title": "Attended Sysupgrade Server",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# Server statistics over 24h\n\nPlease reach out if you need any other stats than shown here, this is currently just a gimmick.\n\nThe raw data is available under [`/metrics`](http://sysupgrade.kyarucloud.moe/metrics)"
   }
  },
  {
   "title": "Builds",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(builds_total[$__range]))"
    }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(cache_hits[$__range]) / (increase(cache_hits[$__range]) + increase(cache_misses[$__range]))"
    }
   ]
  },
  {
   "title": "Most requested profiles",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (profile) (increase(builds_total[$__range])) > 1",
     "legendFormat": "{{profile}}"
    }
   ]
  },
  {
   "title": "Builds Total by Release",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (version) (increase(builds_total[$__range]))",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Most requested targets",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (target) (increase(builds_total[$__range])) > 1",
     "legendFormat": "{{profile}}"
    }
   ]
  },
  {
   "title": "Request per client total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by (name, version) (increase(clients_total[$__range])) > 1",
     "legendFormat": "{{name}} - {{version}}"
    }
   ]
  }
 ]
}