version: "2"

services:
  server:
    image: "asu:latest"
    build:
      context: ./
      dockerfile: Containerfile
    restart: always
    environment:
      - REDIS_URL=redis://redis/
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - "./public:/app/public:ro,rshared"
    depends_on:
      - redis

  worker:
    image: "asu:latest"
    build:
      context: ./
      dockerfile: Containerfile
    restart: always
    command: rqworker --logging_level INFO
    environment:
      - CONTAINER_HOST=unix:///run/user/1000/podman/podman.sock
      - REDIS_URL=redis://redis/
    volumes:
      - "./public:/app/public:rw,rshared"
      - "/run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock:rw"
    depends_on:
      - redis

  # worker2:
  #   image: "asu:latest"
  #   build:
  #     context: ./
  #     dockerfile: Containerfile
  #   restart: always
  #   command: rqworker --logging_level INFO
  #   environment:
  #     - CONTAINER_HOST=unix:///run/user/1000/podman/podman.sock
  #     - REDIS_URL=redis://redis/
  #   volumes:
  #     - "./public:/app/public:rw,rshared"
  #     - "/run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock:rw"
  #   depends_on:
  #     - redis

  redis:
    image: "docker.io/redis/redis-stack-server"
    restart: always
    volumes:
      - "./redis:/data/:rw"

  webserver:
    image: caddy
    volumes:
      - "./misc/Caddyfile:/etc/caddy/Caddyfile"
      - "./public/:/site/:ro,rshared"
    ports:
      - "80:80"
    restart: always
    depends_on:
      - server
